---
- hosts: all
  become: yes
  tasks:
  - name: install java6 on ubuntu14
    apt: 
     name: "{{javaonubuntu}}"
     state: present
    when: ansible_os_family =="Debian"

  - name: install java6 on redhat
    yum:
     name: "{{javaonredhat}}"
     state: present
    when: ansible_os_family =="RedHat"
