---
- hosts: all
  become: yes
  vars: 
    myvar1: ramesh
    myvar2: sai
  tasks:
  - name:  display myvar1
    debug:
      msg: "{{myvar1}}"

  - name: display myvar2
    debug:
      msg: "{{myvar2}}"
